### ISSUE TITLE
Deezloader songs download error 

### ISSUE THREAD

**Issue by amitk94** [kmille/deezer-downloader#100]
Hi, I'm using the Deezloader app on Android app my arl got expired and I updated it with a new arl and now the song downloading is not working and it's for any song that I try to download.
Anyone know how can I fix this please?

Thanks in advance.

**Comment by kmille** [comment]
As it still works for me I need more information about your issue. Have you restarted the app? Have you copied the full arl cookie?

**Comment by amitk94** [comment]
Hi, yes. I copied the full arl code. I have also tried reinstalling the app. Nothing is working for now. I also don't know why it's not working. But I realised that when I entered the new arl code almost all the box were empty. For example the download location, the quality of download file, the resolution of album art, the dates seperator, etc. So I manually had to write or choose all those options. I thought maybe the download path is invalid. But I think it's valid as I remember I used the same download path before.

**Comment by kmille** [comment]
I need command line output to give advise...

**Comment by amitk94** [comment]
> I need command line output to give advise...

Hi, could you please send me the app download link? Or the one that you are already using?

**Comment by kmille** [comment]
Please read the docs and follow the instructions: https://github.com/kmille/deezer-downloader/?tab=readme-ov-file#how-to-get-it-up-and-running

**Comment by amitk94** [comment]
Hi, I'm using an Android phone and I would require a genuine working link to download the deezloader app which is working. Please!

**Comment by kmille** [comment]
You can't run it on Android (afaik)

**Comment by amitk94** [comment]
For my windows, it's working fine. I have been using the app in my android phone for a while now. But why I can't use it in my Android phone now? Deezloader for Android doesn't work anymore?

**Comment by kmille** [comment]
I don't know what you me. You confuse me. Sorry I don't have capacity right now.

**Comment by amitk94** [comment]
Sorry, but all my post here was only about the Deezloader app for Android. Since the download is not working in the app anymore so I posted about this issue. Thanks

**Comment by Maxklos** [comment]
This GitHub Repo ist about the Programm **deezer-downloader** not about the app **Deezloader** please contact the right developer to take care about your issue.
