### ISSUE TITLE
Please make READMEs more explicit

### ISSUE THREAD

**Issue by Trakeur** [kmille/deezer-downloader#101]
I'm on Windows and the tool may not have been designed for it, but it's complicated to make it work without spending time and understanding things on your own. 
For example, if you install it with pip, you don't know where the config files are, you don't even know how to launch the tool. 

I don't doubt that the tool is nice, but it's pretty frustrating. I'm putting this here, but it applies to so many github repo.

**Comment by ReXiiuM** [comment]
Did you figure it out? I still don't know how to launch it or find my files...

**Comment by Trakeur** [comment]
I finally decided to try with docker. I managed to launch the tool and access the local web page. Unfortunately the downloads didn't work. I had 403 response (even by setting up the cookie). I stopped here.

**Comment by kmille** [comment]
I don't know how python on Windows works. Please check the docs, but it's possible to run `deezer-downloader` after `pip install`. Then you can `--show-config-template` to show the default config file and redirect it to a file. Then you can use `--config <your config file> to run. You need to adjust the `base = /tmp/deezer-downloader` to a proper directory (in the windows way).

**Comment by kmille** [comment]
And the project still works for me:
```
Worker 0 is now working on task: {'track_id': 8086130, 'add_to_playlist': False}
Downloading 'Adele - Set Fire to the Rain.mp3'
Dowload finished: /tmp/deezer-downloader/songs/Adele - Set Fire to the Rain.mp3
Setting state to mission accomplished to worker 0
worker 0 is done with task: {'track_id': 8086130, 'add_to_playlist': False} (state=mission accomplished)
```
