### ISSUE TITLE
API / URL Only

### ISSUE THREAD

**Issue by modemmike** [kmille/deezer-downloader#102]
Curious if there is a way to just the URL of the full-length media?

**Comment by kmille** [comment]
What do you mean? A download url?

**Comment by modemmike** [comment]
Correct, my intention is to load the media into a local player (VirtualDJ). Basically, streaming without a need to save the file locally.

**Comment by kmille** [comment]
The file is encrypted, so it's not possible.

**Comment by modemmike** [comment]
Ok, thanks for clarifying.
