### ISSUE TITLE
help i don't understand anything

### ISSUE THREAD

**Issue by Artyaom** [kmille/deezer-downloader#103]
i need help to run the app... launched all the commands needed to install and all that stuff but how do i open it with interface and all... i just have a directory with project files

**Comment by kmille** [comment]
How do you run it?
Please give me command line output?
I only can give advise to Linux computers.
You need some basic knowlegde about computers..

**Comment by Artyaom** [comment]
i don't ! i managed to install via git command and then your pip command installation, then just have the directory
i tried on windows and macOS
the help command you provided can't work on my python there is a 'syntax error'
and i can't find the settings file mentioned on the readme, so can't configure arl and all that stuff

**Comment by kmille** [comment]
Sorry I only know about Linux.

**Comment by Dan-Wood** [comment]
Grab the docker image, it might be easier for you.
