### ISSUE TITLE
How to use docker image?

### ISSUE THREAD

**Issue by javi242** [kmille/deezer-downloader#108]
Hi, I installed docker on my Mac, then executed:

docker pull kmille2/deezer-downloader

and then:

mkdir downloads
sudo docker run -p 5000:5000 --volume $(pwd)/downloads/:/mnt/deezer-downloader --env DEEZER_COOKIE_ARL=changeme kmille2/deezer-downloader:latest 
xdg-open http://localhost:5000

replacing "changeme" with my arl cookie. 

Then opened http://localhost:5000/ in Chrome and when I try to download a playlist I always get this error in all tracks:

ERROR: Can not download this song. Got a 403

Under "downloads" some folders have been created: "albums", "playlists", "songs", "youtube-dl", "zips"

If I enter "playlists" folder there is a folder with my playlist, but it only contains a m3u8 file.

Am I doing something wrong or maybe I'm missing something? Do I need the settings.ini file when using docker? If so, where do I need to put this file? Thanks in advance.

**Comment by javi242** [comment]
Ok now I got it working, using a free account, but the quality is 128. Is there a way to download using my premium account so the quality is 320? Thanks in advance.

**Comment by kmille** [comment]
See this comment and the following: https://github.com/kmille/deezer-downloader/issues/66#issuecomment-2002309521
