### ISSUE TITLE
ERROR: we are not logged in on deezer.com. Please update the cookie'

### ISSUE THREAD

**Issue by NickKruto** [kmille/deezer-downloader#113]

**Comment by NickKruto** [comment]
![image](https://github.com/user-attachments/assets/5bd6b4c8-4cd2-4550-aa70-0d8f300f7426)
![image](https://github.com/user-attachments/assets/aba329d3-a00c-4b16-8c06-482b62951ef9)
And?

**Comment by kmille** [comment]
- Does the cookie work in the browser
- Does the cookie belong to a free subscription? Paid subscription does not work.

**Comment by NickKruto** [comment]
Yes, cookies work in the browser. I have a free subscription

**Comment by kmille** [comment]
Sorry I can't reproduce. It works for me right now ...
