### ISSUE TITLE
More info required for basic use

### ISSUE THREAD

**Issue by dylansutterlin** [kmille/deezer-downloader#114]
Hello, thanks for this tool! It seems nice but unfortunately I was not able to get it running.

I have use the pip way of downloading the package, and have modified the config file with my deezer arl key.

Running `deezer-downloader -c deezer-downloader.ini` got me the following output : 
```
/home/dsutterlin/.local/lib/python3.10/site-packages/giphypop.py:241: UserWarning: You are using the giphy public api key. This should be used for testing only and may be deactivated in the future. See https://github.com/Giphy/GiphyAPI.
  warnings.warn('You are using the giphy public api key. This '
Worker 0 is waiting for a task
Worker 1 is waiting for a task
Worker 3 is waiting for a task
Worker 2 is waiting for a task
```
I tried many different ways to input the URL to a deezer playlist ( in the config file) but was not sure where to input such information.
Sorry for opening such a "basic" issue, I am really looking foward to use this tool. 

Thanks for any tips on where to input the URLs to download

**Comment by cyber-g** [comment]
I also faced the issue... I figured out that you just need to open a web browser to http://127.0.0.1:5000/

**Comment by GingrPowr** [comment]
I agree, it's never explained what this python package actually _is_: a collection of python scripts to download several video/song on several online services **through a web backend GUI**.
@kmille, you could:
- specify this in the readme
- specify this in the --help
- specify it at launch
- make the code open the backend on the default web browser at launch (if you already implemented that on Linux, know that it's not working on Windows)
Because without any hint, people will think this works through a CLI, like most Python packages.
With that cleared, you will have a lot less people asking for directions.

**Comment by boboliiii** [comment]
totally agree with the comment above, this program is kickass, but it's really not clear how to get it started the first time.

for me it was:
put the arl key in deezer-downloader.ini.template

also in the template putting the path to youtubedl (like command = .....\Python\Python310\Lib\site-packages\yt_dlp) (yes this works on windows, even thought the example path looks very unix-y)

running deezer.downloader -c PATH\TO\deezer-downloader.ini.template

if it works it'll say something about Worker 0 waiting for task.  

then go into your web browser and load http://127.0.0.1:5000/

works great

**Comment by kmille** [comment]
Feel free to update the dos and create a PR. For me everything is in the REAMDE:
> There is a settings file template called settings.ini.example

> poetry run deezer-downloader --config settings.ini

**Comment by GingrPowr** [comment]
@kmille I just wrote a new ReadMe for the github, planning on doing something similar for --help. Do I open a new branch?

**Comment by kmille** [comment]
sure, just create a Merge Request

**Comment by GingrPowr** [comment]
Pull request #123
Let me know if you are not 100% OK with the proposition.

**Comment by GingrPowr** [comment]
@dylansutterlin, @cyber-g, @boboliiii, @kmille: see also #124.

**Comment by kmille** [comment]
Done in https://github.com/kmille/deezer-downloader/pull/123
