### ISSUE TITLE
Invalid encoding of filename for Unicode characters

### ISSUE THREAD

**Issue by redmanmale** [kmille/deezer-downloader#17]
Original artist and song name: **Дайте Танк (!) - Мы**
Filename: **Ð”Ð°Ð¹Ñ‚Ðµ Ð¢Ð°Ð½Ðº (!) - ÐœÑ‹.mp3**

Looks like a classic python2 unicode issue.

**Comment by kmille** [comment]
Hey,
I can not reproduce the issue. Can you reproduce it? Do you still use python2? In the meantime the project was migrated to python3. I switched the default branch to python3
