### ISSUE TITLE
Login does not seem to work anymore

### ISSUE THREAD

**Issue by KirovAir** [kmille/deezer-downloader#2]
`We are not logged in`
`Do the login`
`Login was not successfull`

Probably a Deezer update.

**Comment by kmille** [comment]
It still works for me. Please try it again or try to debug it. Check out deezer_login.py

**Comment by KirovAir** [comment]
I did some digging and it seems the login has been blocked for accounts from my country (NL). Using a VPN and a new account made using that VPN it works!

**Comment by KirovAir** [comment]
Whoops a small question: Is it possible to remove this issue? I forgot to login with my other github account. This is one also used for work-related things which includes a music service.. I don't think they will be happy to see this post in a piracy-related tool. ^^;
