### ISSUE TITLE
No module named 'mpd' error while starting

### ISSUE THREAD

**Issue by f2k1de** [kmille/deezer-downloader#22]
When running the app I get this error. 
Commenting out line for in app/music_backend.py worked for me, because I didn't needed any mpd stuff.  
```
vagrant@buster:~$ /opt/deezer/app/venv/bin/python /opt/deezer/app/app.py
Traceback (most recent call last):
  File "/opt/deezer/app/app.py", line 10, in <module>
    from music_backend import sched
  File "/opt/deezer/app/music_backend.py", line 4, in <module>
    import mpd
ModuleNotFoundError: No module named 'mpd'
```

**Comment by kmille** [comment]
Do you use the Vagrantfile?
Can you make a `opt/deezer/app/venv/bin/python -m pip list`? It looks like you missed the `source /opt/deezer/app/venv/bin/activate && pip install -r /opt/deezer/requirements.txt` command
