### ISSUE TITLE
C Compiler is needed for pycrypto

### ISSUE THREAD

**Issue by f2k1de** [kmille/deezer-downloader#23]
When there is no C Compiler in Path (like it is the case in the Vagrantfile) the requirement pycrypto can not be installed.

**Comment by kmille** [comment]
I used the Vagrantfile several times (just by using vagrant up) and never had that problem. 
Can you show me the output of `vagrant up`?

**Comment by f2k1de** [comment]
https://gist.github.com/f2k1de/8e901745203b14d8d0c9af55ecef1c88#file-gistfile1-txt-L553

**Comment by kmille** [comment]
I use `vagrant-scp` which automatically installs the VirtualBox-Guest-Tools and needs gcc. That's why I did not have the issue.

```bash
kmille@linbox deezer-downloader master % vagrant plugin list
vagrant-scp (0.5.7, global)
vagrant-vbguest (0.24.0, global)
```
