### ISSUE TITLE
flac files

### ISSUE THREAD

**Issue by K3nn3th2** [kmille/deezer-downloader#28]
is it possible to get flac files also?

**Comment by kmille** [comment]
Try to uncomment this line: https://github.com/kmille/deezer-downloader/blob/master/app/deezer.py#L335

But it's only supported with a premium subscription. I think at least.

**Comment by K3nn3th2** [comment]
deezer also offers flac to free users.
i just tried your hint, using a value of 9 instead of 8 it works.
it is still saved with an mp3 ending, though. 

maybe you could update your program?

**Comment by kmille** [comment]
ah nice! Thanks for the Pull Request.

**Comment by kmille** [comment]
I merged it #31 
Thank you!
