### ISSUE TITLE
Usage of mpd unclear.

### ISSUE THREAD

**Issue by ZaxonXP** [kmille/deezer-downloader#29]
In the help file on github it is described that it is possible to use mpd together with the `deezer-downloader`. However it is not clear for me if mpd can be used to search Deezer and download/play from it or it is only used as a player after the album/songs are downloaded using web interface and deezer-downloader. Please clarify.

I would like to use the Deezer from linux console only, but I am not sure if it is possible or it always the web gui has to be used.

Regards,
Piotr

**Comment by kmille** [comment]
Hey,
with the deezer-downloader you can search and download music. MPD only works with a local database of music which was downloaded previously.
If you want to use it from the command line there are two possibilities:
- run the deezer-downloader in a Docker container and use its rest api
- build a wrapper around the functions of in [music_backend.py](https://github.com/kmille/deezer-downloader/blob/master/app/music_backend.py#L202). You may have to adjust some minor things.
