### ISSUE TITLE
ARL instead of SID

### ISSUE THREAD

**Issue by K3nn3th2** [kmille/deezer-downloader#30]
other python deezer projects seem to prefer using the ARL instead of the SID . they also dont implement a thread to keep the session alive.

Would the use of it make the dedicated thread obsolete?
or is there anything i'm missing here? please correct me if i'm wrong.

**Comment by kmille** [comment]
Can you explain me what ARL is? Thank you.

**Comment by kmille** [comment]
Hey 
I moved to the `arl` cookie in d986460e7d889dede56eef4614a63b47872007cc
