### ISSUE TITLE
[Feature request] Favorite tracks playlist downloading

### ISSUE THREAD

**Issue by redmanmale** [kmille/deezer-downloader#34]
with url like this: `https://www.deezer.com/us/profile/%numeric_user_id%/loved`

**Comment by kmille** [comment]
At least for my profile I'm the only one has access to my favorite tracks (others get a "This profile is set to private."). Do you know how I can switch this to pubic?

**Comment by redmanmale** [comment]
You can get all favorite tracks from any user here: https://api.deezer.com/user/%user_id%/tracks

**Comment by kmille** [comment]
does not work for me (even in my own browser session):
{"error":{"type":"OAuthException","message":"An active access token must be used. This user's profile is private","code":200}}

**Comment by redmanmale** [comment]
That's strange.
For example:
https://api.deezer.com/user/705965861/tracks

I tried with or without my browser session, different browsers, here's screenshot via Postman.
![image](https://user-images.githubusercontent.com/6782721/97814866-58c8df00-1c9b-11eb-9273-8a6ad0868130.png)

**Comment by kmille** [comment]
Indeed. I will recheck it the next days

**Comment by kmille** [comment]
`https://api.deezer.com/user/%user_id%/tracks` does work for my free test account. But it does not work for my own private premium account. Do you know if there is a switch in the settings? I couldn't find one.

**Comment by kmille** [comment]
I am implementing the feature right now and have a problem: Your account has two fav songs. The second one is fine but I can't download it the first one because `https://www.deezer.com/de/track/75461497` returns a 404. Can you play the song in the browser or is this a special song?

**Comment by kmille** [comment]
functionality added in https://github.com/kmille/deezer-downloader/commit/e764ea6355cfda8ffa272a6c4bb733113e0dbf50

**Comment by redmanmale** [comment]
Thanks mate, that's great!
