### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by ohjasry** [kmille/deezer-downloader#4]
My Credentials are correct, I am able to login on deezer.com

$HomeIP - - [27/Apr/2019 21:25:22] "POST /api/v1/deezer/download HTTP/1.1" 200 -
We are not logged in
Do the login
Login was not successfull
Downloading song 73519924
Downloading song Mindless Self Indulgence - Never Wanted To Dance.mp3
ERROR downloading from https://e-cdns-proxy-%s.dzcdn.net/mobile/1: 'MD5_ORIGIN'

**Comment by kmille** [comment]
"Login was not successfull"
See: https://github.com/kmille/deezer-downloader/blob/master/README.md
Deezer now uses a Captcha for the login. The app caches the Login-Session but after some idle time the you get logged out. 
A fix would be something like: a cronjob that makes a request to the backend. The lifetime of the cookie/session is managed by the backend. The sid cookie itself has no expire date.

**Comment by kmille** [comment]
cronjob works. checkout the systemd folder
