### ISSUE TITLE
[Docker on Synology] PermissionError: [Errno 13] Permission denied: '/mnt/deezer-downloader/songs'

### ISSUE THREAD

**Issue by NovalisVonHardenberg** [kmille/deezer-downloader#48]
Hello,
installed the Docker container on my Synology NAS. But unfortunately the following error message appears when starting:
PermissionError: [Errno 13] Permission denied: '/mnt/deezer-downloader/songs'
The following settings do not help either:
![image](https://user-images.githubusercontent.com/67534367/109138690-ece31880-775a-11eb-8ed5-67b999bd92a4.png)
1026 is the UID of admin-user.

**Comment by kmille** [comment]
Hey
this is described in the [Readme](https://github.com/kmille/deezer-downloader/#docker). You can
- `chmod 777` the downloads directory on the host
- or change a line in the Dockerfile: `RUN useradd -s /bin/bash deezer -u 1026`
