### ISSUE TITLE
sid cookie

### ISSUE THREAD

**Issue by 89z** [kmille/deezer-downloader#49]
I see previously this project used the `sid` cookie, and now uses the `arl` cookie. I was wondering if anyone did testing on the expiration of the `sid` cookie.

I have only done limited testing, but I know that it does stay alive for at least four hours.

If it stays alive for a while, it might be a good option, as you could avoid the `deezer.getUserData` call:

https://github.com/kmille/deezer-downloader/blob/4418bc1064da5eff3452e227f5c4d26c4771a757/app/deezer.py#L462-L463

**Comment by 89z** [comment]
After some more testing, it seems the life is about three hours from last use, so if you use it at least every three hours, it should stay alive. I would have to do more testing to know for sure, but at any rate, doesnt seem like a good option.

**Comment by kmille** [comment]
Hey,
if I recall correctly:
- `sid` expires after some hours, but the cookie automatically extend its lifetime (serverside) if you send requests with it
-  I think the `arl` cookie is valid for some months even if you don't use it for a month

See also this https://github.com/kmille/deezer-downloader/issues/30
