### ISSUE TITLE
How to download Deezer Playlist as FLACs

### ISSUE THREAD

**Issue by ILikeStars** [kmille/deezer-downloader#53]
Hi, I have a question... I didn't really get anything in the How to Use and I kind of want to download my favourite songs as FLACs, can anyone do a tutorial(video) or a detailed guide to help? xD

**Comment by ILikeStars** [comment]
I looked through the How  to Use again, but i really don't get what i need to do. I haven't done something like this before, so please help!

**Comment by kmille** [comment]
https://github.com/kmille/deezer-downloader/blob/4418bc1064da5eff3452e227f5c4d26c4771a757/app/settings.ini.example#L45-L46
