### ISSUE TITLE
Spotify downloader isn't downloading the full playlist

### ISSUE THREAD

**Issue by fugkco** [kmille/deezer-downloader#55]
Hello,

I tried downloading a playlist from a Spotify playlist. It didn't seem to retrieve the full list. Logs say it has 100 `We got 100 songs from the Spotify playlist`. Retrying it doesn't work as it just says all the items already exist. Is there any way to download the rest?

Thanks

**Comment by kmille** [comment]
Is it still an issue? I think it should be fixed now.

**Comment by fugkco** [comment]
Yes that's right. This can be closed.

-------- Original Message --------
On 11 Apr 2021, 20:05, kmille < ***@***.***> wrote:
Is it still an issue? I think it should be fixed now.
