### ISSUE TITLE
Can't use downloaded mp3's in Ableton Live 11

### ISSUE THREAD

**Issue by Gwynei** [kmille/deezer-downloader#59]
Ableton Live 11 doesn't accept mp3's downloaded with deezer-downloader.

Error messages in Ableton:
![image](https://user-images.githubusercontent.com/5103328/120197650-79e9b200-c221-11eb-9e9c-76e1df8ac0aa.png)

(_pn suffix is added using Platinum Notes, but same error occurs before mastering the track)

Only workaround is that I decode/encode all downloaded mp3's with ffmpeg manually. After I do that, the mp3 will load into Ableton.

I can't really find the reason why Ableton doesn't accept these mp3's, because the MP3's play absolutely fine in any random media player.

**Comment by dejan995** [comment]
Hello,
Did you look on this webpage [https://help.ableton.com/hc/en-us/articles/209774325](https://help.ableton.com/hc/en-us/articles/209774325)?
They list the most common issues why Ableton can't import files.
I haven't used Ableton in a long time but I tried to import some FLAC songs I download with deezer-downloader in FL-Studio and they work perfectly.
This looks like an Ableton Live issue but I can't be 100% sure.

**Comment by kmille** [comment]
I don't see any issue here on our site and will close this
