### ISSUE TITLE
Help me with installing.

### ISSUE THREAD

**Issue by GooglesXmaddness** [kmille/deezer-downloader#63]
Hello, I'm looking really forward to using this app, but I have no Idea how to install and run it. Could someone please help me?

**Comment by kmille** [comment]
Please read the docs (README.md). It tells you how to use it with docker, vagrant or just in a virtual environment.

**Comment by GooglesXmaddness** [comment]
The problem is, that I tried, and I get countless of errors. Should I try it in cmd? Beacuse I only tried it in digital ocean droplet console

**Comment by kmille** [comment]
I don't have experience with the digital ocean droplet console. A Linux (e.g Debian/Ubuntu/Apline/Arch) is required. And some basic linux command line skills. But you can use the Dockerhub image if you like. Just check the docs.
