### ISSUE TITLE
how to use API

### ISSUE THREAD

**Issue by tonyt321** [kmille/deezer-downloader#73]
I am trying to figure out how to use the simple REST api but don't know how to reach it.

**Comment by kmille** [comment]
You can check [app/app.py](https://github.com/kmille/deezer-downloader/blob/a5164b57cb95b5cf8c0299072b088963166a889d/app/app.py) or use the frontend in the brwoser and check the browsers debug console (check the network tab).

**Comment by tonyt321** [comment]
I am always getting

error: "add_to_playlist must be a boolean"

msg.payload = {
'playlist_name': 'emby add',
'playlist_url': 'https://open.spotify.com/track/4TjWyfp9lWll6VzccPbjYY?si=f00pGGnYRIaRI-emvDxx2A',
'add_to_playlist': 'False',
'create_zip': 'False'
}

//set url
msg.url = "http://192.168.1.21:8093/playlist/spotify"

**Comment by kmille** [comment]
>  'add_to_playlist': 'False',
it looks like you are using 'False' as a string. Try False/false
