### ISSUE TITLE
Incomplete statement [ERR_CONNECTION_REFUSED].

### ISSUE THREAD

**Issue by msebastian100** [kmille/deezer-downloader#77]
Incomplete statement [ERR_CONNECTION_REFUSED].
https://github.com/kmille/deezer-downloader
I am not a Docker user and then it is noticeable that in the instructions ubuntu "packages" were omitted.
If you then managed to get the startup then you get the error in the browser [ERR_CONNECTION_REFUSED].

**Comment by kmille** [comment]
Can you show me your comand line output? So what are you doing exaclty? I need some more info to help.
