### ISSUE TITLE
standard_init_linux.go:228: exec user process caused: exec format error

### ISSUE THREAD

**Issue by dannyvfilms** [kmille/deezer-downloader#80]
Followed the setup guide for Docker deployment on Raspberry Pi 4. I'm pretty sure this error means that ARM is not supported. Am I remembering that correctly?
```
mkdir downloads
sudo docker run -p 5000:5000 --volume $(pwd)/downloads/:/mnt/deezer-downloader --env DEEZER_COOKIE_ARL=redacted kmille2/deezer-downloader:latest 
xdg-open http://localhost:5000```

**Comment by kmille** [comment]
Can you show me the whole command and output?

**Comment by steampixel** [comment]
Alternatively you can clone the image to the folder "deezer-downloader" and build the docker image on your own using this flag: "-platform linux/arm64" directly on your raspberry pi.

`docker build --platform linux/arm64 -t custom-deezer-downloader deezer-downloader`

Then run the container with the new image on your raspberry pi:

`docker run -d -p 5000:5000 --volume "$(pwd)"/downloads:/mnt/deezer-downloader --env DEEZER_COOKIE_ARL=XXXX custom-deezer-downloader`
