### ISSUE TITLE
Can't download any song get always 403 Error

### ISSUE THREAD

**Issue by F0ob4r** [kmille/deezer-downloader#82]
I tried several songs to download. I get for every single File a 403 Error

**Comment by kmille** [comment]
can you give an example please and be more precise

**Comment by F0ob4r** [comment]
You're fast ;)

User request: /search with {'type': 'track', 'query': 'hurra hurra die pest'}
User request: /download with {'type': 'track', 'music_id': 1609903492, 'add_to_playlist': False, 'create_zip': False}
Worker 0 is now working on task: {'track_id': 1609903492, 'add_to_playlist': False}
Downloading 'Feuerschwanz - Hurra Hurra die Pest ist da.mp3'
ERROR: Can not download this song. Got a 403
worker 0 is done with task: {'track_id': 1609903492, 'add_to_playlist': False} (state=mission accomplished)
Worker 0 is waiting for a task

User request: /download with {'type': 'track', 'music_id': 3145739, 'add_to_playlist': False, 'create_zip': False}
Worker 0 is now working on task: {'track_id': 3145739, 'add_to_playlist': False}
Downloading 'Genesis - Invisible Touch.mp3'
ERROR: Can not download this song. Got a 403
worker 0 is done with task: {'track_id': 3145739, 'add_to_playlist': False} (state=mission accomplished)


User request: /search with {'type': 'album', 'query': 'heitz'}
User request: /download with {'type': 'album', 'music_id': 346782027, 'add_to_playlist': False, 'create_zip': False}
Worker 1 is now working on task: {'album_id': 346782027, 'add_to_playlist': False, 'create_zip': False}
Downloading 'Markus Heitz - Kapitel 1 - Das Herz der Zwerge 1.mp3'
ERROR: Can not download this song. Got a 403
Downloading 'Markus Heitz - Kapitel 2 - Das Herz der Zwerge 1.mp3'
ERROR: Can not download this song. Got a 403
Downloading 'Markus Heitz - Kapitel 3 - Das Herz der Zwerge 1.mp3'
ERROR: Can not download this song. Got a 403
Downloading 'Markus Heitz - Kapitel 4 - Das Herz der Zwerge 1.mp3'
ERROR: Can not download this song. Got a 403
Downloading 'Markus Heitz - Kapitel 5 - Das Herz der Zwerge 1.mp3'
ERROR: Can not download this song. Got a 403
Downloading 'Markus Heitz - Kapitel 6 - Das Herz der Zwerge 1.mp3'
ERROR: Can not download this song. Got a 403


How can I be more precise? Is it possible to be more verbose with the app?

**Comment by F0ob4r** [comment]
I used the Website generated by deezer-downloader

**Comment by F0ob4r** [comment]
If I use the search like you did I get no Response:

[2022-11-15 13:32:59 +0000] [21406] [DEBUG] POST /search
User request: /search with {'type': 'track', 'query': 'hurra hurra die pest'}

Response is empty:
[]

**Comment by F0ob4r** [comment]
I did a research at api.deezer.com:
ID is the same i got..

GET https://api.deezer.com/search?q=track:"hurra hurra die pest" 
ANSWER:
{
  "data": [
    {
      "id": "**1609903492**",
      "readable": true,
      "title": "Hurra Hurra die Pest ist da",
      "title_short": "Hurra Hurra die Pest ist da",
      "title_version": "",
      "link": "https://www.deezer.com/track/1609903492",
      "duration": "257",
      "rank": "370850",
      "explicit_lyrics": false,
      "explicit_content_lyrics": 0,
      "explicit_content_cover": 0,
      "preview": "https://cdns-preview-9.dzcdn.net/stream/c-9dc29b334bc17d07448f7c42470e51ec-4.mp3",
      "md5_image": "5a197aa2ff36dd90127251e5862270cd",
      "artist": {
        "id": "327953",
        "name": "Feuerschwanz",
        "link": "https://www.deezer.com/artist/327953",
        "picture": "https://api.deezer.com/artist/327953/image",
        "picture_small": "https://e-cdns-images.dzcdn.net/images/artist/8b90b63d87c558be8068c9e6443f6059/56x56-000000-80-0-0.jpg",
        "picture_medium": "https://e-cdns-images.dzcdn.net/images/artist/8b90b63d87c558be8068c9e6443f6059/250x250-000000-80-0-0.jpg",
        "picture_big": "https://e-cdns-images.dzcdn.net/images/artist/8b90b63d87c558be8068c9e6443f6059/500x500-000000-80-0-0.jpg",
        "picture_xl": "https://e-cdns-images.dzcdn.net/images/artist/8b90b63d87c558be8068c9e6443f6059/1000x1000-000000-80-0-0.jpg",
        "tracklist": "https://api.deezer.com/artist/327953/top?limit=50",
        "type": "artist"
      },
      "album": {
        "id": "284871512",
        "title": "Metvernichter",
        "cover": "https://api.deezer.com/album/284871512/image",
        "cover_small": "https://e-cdns-images.dzcdn.net/images/cover/5a197aa2ff36dd90127251e5862270cd/56x56-000000-80-0-0.jpg",
        "cover_medium": "https://e-cdns-images.dzcdn.net/images/cover/5a197aa2ff36dd90127251e5862270cd/250x250-000000-80-0-0.jpg",
        "cover_big": "https://e-cdns-images.dzcdn.net/images/cover/5a197aa2ff36dd90127251e5862270cd/500x500-000000-80-0-0.jpg",
        "cover_xl": "https://e-cdns-images.dzcdn.net/images/cover/5a197aa2ff36dd90127251e5862270cd/1000x1000-000000-80-0-0.jpg",
        "md5_image": "5a197aa2ff36dd90127251e5862270cd",
        "tracklist": "https://api.deezer.com/album/284871512/tracks",
        "type": "album"
      },
      "type": "track"
    },
    {
      "id": "797258612",
      "readable": true,
      "title": "Hurra Hurra die Pest ist da (Live aus dem E-Werk)",
      "title_short": "Hurra Hurra die Pest ist da",
      "title_version": "(Live aus dem E-Werk)",
      "link": "https://www.deezer.com/track/797258612",
      "duration": "348",
      "rank": "126169",
      "explicit_lyrics": false,
      "explicit_content_lyrics": 0,
      "explicit_content_cover": 2,
      "preview": "https://cdns-preview-4.dzcdn.net/stream/c-4efae9dd9165abc46f457b7b5bb1a7d2-4.mp3",
      "md5_image": "1e85fa6b4e61f00e948a6cf45f077822",
      "artist": {
        "id": "327953",
        "name": "Feuerschwanz",
        "link": "https://www.deezer.com/artist/327953",
        "picture": "https://api.deezer.com/artist/327953/image",
        "picture_small": "https://e-cdns-images.dzcdn.net/images/artist/8b90b63d87c558be8068c9e6443f6059/56x56-000000-80-0-0.jpg",
        "picture_medium": "https://e-cdns-images.dzcdn.net/images/artist/8b90b63d87c558be8068c9e6443f6059/250x250-000000-80-0-0.jpg",
        "picture_big": "https://e-cdns-images.dzcdn.net/images/artist/8b90b63d87c558be8068c9e6443f6059/500x500-000000-80-0-0.jpg",
        "picture_xl": "https://e-cdns-images.dzcdn.net/images/artist/8b90b63d87c558be8068c9e6443f6059/1000x1000-000000-80-0-0.jpg",
        "tracklist": "https://api.deezer.com/artist/327953/top?limit=50",
        "type": "artist"
      },
      "album": {
        "id": "117690062",
        "title": "Best Of",
        "cover": "https://api.deezer.com/album/117690062/image",
        "cover_small": "https://e-cdns-images.dzcdn.net/images/cover/1e85fa6b4e61f00e948a6cf45f077822/56x56-000000-80-0-0.jpg",
        "cover_medium": "https://e-cdns-images.dzcdn.net/images/cover/1e85fa6b4e61f00e948a6cf45f077822/250x250-000000-80-0-0.jpg",
        "cover_big": "https://e-cdns-images.dzcdn.net/images/cover/1e85fa6b4e61f00e948a6cf45f077822/500x500-000000-80-0-0.jpg",
        "cover_xl": "https://e-cdns-images.dzcdn.net/images/cover/1e85fa6b4e61f00e948a6cf45f077822/1000x1000-000000-80-0-0.jpg",
        "md5_image": "1e85fa6b4e61f00e948a6cf45f077822",
        "tracklist": "https://api.deezer.com/album/117690062/tracks",
        "type": "album"
      },
      "type": "track"
    },
    {
      "id": "96456856",
      "readable": true,
      "title": "Hurra Hurra die Pest ist da (Live aus dem E-Werk)",
      "title_short": "Hurra Hurra die Pest ist da",
      "title_version": "(Live aus dem E-Werk)",
      "link": "https://www.deezer.com/track/96456856",
      "duration": "348",
      "rank": "107720",
      "explicit_lyrics": false,
      "explicit_content_lyrics": 0,
      "explicit_content_cover": 2,
      "preview": "https://cdns-preview-5.dzcdn.net/stream/c-5aed6b19f8510a0dd930276dc29b353f-4.mp3",
      "md5_image": "8131d581ddd7bc5e5a6ff51567dc0efa",
      "artist": {
        "id": "327953",
        "name": "Feuerschwanz",
        "link": "https://www.deezer.com/artist/327953",
        "picture": "https://api.deezer.com/artist/327953/image",
        "picture_small": "https://e-cdns-images.dzcdn.net/images/artist/8b90b63d87c558be8068c9e6443f6059/56x56-000000-80-0-0.jpg",
        "picture_medium": "https://e-cdns-images.dzcdn.net/images/artist/8b90b63d87c558be8068c9e6443f6059/250x250-000000-80-0-0.jpg",
        "picture_big": "https://e-cdns-images.dzcdn.net/images/artist/8b90b63d87c558be8068c9e6443f6059/500x500-000000-80-0-0.jpg",
        "picture_xl": "https://e-cdns-images.dzcdn.net/images/artist/8b90b63d87c558be8068c9e6443f6059/1000x1000-000000-80-0-0.jpg",
        "tracklist": "https://api.deezer.com/artist/327953/top?limit=50",
        "type": "artist"
      },
      "album": {
        "id": "9816572",
        "title": "10 Jahre Feuerschwanz Live",
        "cover": "https://api.deezer.com/album/9816572/image",
        "cover_small": "https://e-cdns-images.dzcdn.net/images/cover/8131d581ddd7bc5e5a6ff51567dc0efa/56x56-000000-80-0-0.jpg",
        "cover_medium": "https://e-cdns-images.dzcdn.net/images/cover/8131d581ddd7bc5e5a6ff51567dc0efa/250x250-000000-80-0-0.jpg",
        "cover_big": "https://e-cdns-images.dzcdn.net/images/cover/8131d581ddd7bc5e5a6ff51567dc0efa/500x500-000000-80-0-0.jpg",
        "cover_xl": "https://e-cdns-images.dzcdn.net/images/cover/8131d581ddd7bc5e5a6ff51567dc0efa/1000x1000-000000-80-0-0.jpg",
        "md5_image": "8131d581ddd7bc5e5a6ff51567dc0efa",
        "tracklist": "https://api.deezer.com/album/9816572/tracks",
        "type": "album"
      },
      "type": "track"
    }
  ],
  "total": 3
}

**Comment by kmille** [comment]
> If I use the search like you did I get no Response:
> 
> [2022-11-15 13:32:59 +0000] [21406] [DEBUG] POST /search User request: /search with {'type': 'track', 'query': 'hurra hurra die pest'}
> 
> Response is empty: []

Can't reproduce that. I need more information. Can you describe your environment? Docker? Commit? OS? Command line output

**Comment by F0ob4r** [comment]
I tried it by fresh manual install and also with docker

**Comment by kmille** [comment]
- Can you download other songs or do you get a 403 for every song?
- Please show me your settings file
- Please show me your commit you are working with
- Please show me the whole command line output

**Comment by TheHBF** [comment]
Hi,
I have also the same problem with a Docker instance (not tried with another way).

The logs about one of Ariana Grande song:

```
User request: /search with {'type': 'track', 'query': 'ariana'}
User request: /download with {'type': 'track', 'music_id': 629899842, 'add_to_playlist': False, 'create_zip': False}
Worker 3 is now working on task: {'track_id': 629899842, 'add_to_playlist': False}
Downloading 'Ariana Grande - 7 rings.mp3'
ERROR: Can not download this song. Got a 403
worker 3 is done with task: {'track_id': 629899842, 'add_to_playlist': False} (state=mission accomplished)
Worker 3 is waiting for a task
```

Content of settings file into docker container:
```
deezer@2d0092db62ea:/opt/deezer/app$ cat settings.ini
;;; base config

[mpd]
; if you set this to True, the backend will connect to mpd (localhost:6600) and update
; the music database after a completed download
use_mpd = False
host = localhost
port = 6600
music_dir_root = /mnt/deezer-downloader

[download_dirs]
base = /mnt/deezer-downloader

songs = %(base)s/songs
albums = %(base)s/albums
zips = %(base)s/zips
playlists = %(base)s/playlists
youtubedl = %(base)s/youtube-dl

[debug]
; debug output used for /debug
command = journalctl -u deezer-downloader -n 100 --output cat

[http]
; flask options
host = 127.0.0.1
port = 5000
debug = False

; if used behind a proxy, specify base url prefix
; url_prefix = /deezer
url_prefix = 
api_root = %(url_prefix)s
static_root = %(url_prefix)s/static

[threadpool]
; number of workers in thread pool, this specifies the maximum number of parallel downloads
workers = 4

[deezer]
; valid arl cookie value
; login manually using your web browser and take the arl ookie
cookie_arl = [a-f0-9]{192}

[youtubedl]
# you have to keep it up-to date manually!
#command = /home/kmille/projects/deezer-downloader/app/venv/bin/yt-dlp
command = /opt/deezer/app/venv/bin/yt-dlp




; vim: syntax=dosini
```
My docker run command:
`docker run -p 5006:5000 --volume /home/me/Musique/downloads:/mnt/deezer-downloader --env DEEZER_COOKIE_ARL=my_cookie_arl_value_valid_until_2023 --name dzdl kmille2/deezer-downloader:latest`

**Comment by TheHBF** [comment]
Just tried with ARL cookie of a free account (like it has been done for https://github.com/kmille/deezer-downloader/issues/66). It works.
So does it not work with a premium account?

**Comment by kmille** [comment]
Yes, that's true. But I can't tell you why /o\

**Comment by F0ob4r** [comment]
Sorry, I can't test at the moment. I have to restore my environment and there is not enough time at the moment.

**Comment by rjwonder** [comment]
Is this not very much related? https://github.com/godeezer/lib/issues/11

They are speaking about a missing "licence_token"

**Comment by csimpi** [comment]
same for me, any updates on this?

**Comment by csimpi** [comment]
be aware, using free user token will download files only in 128k, so even using any youtube or spotify downloader will result the same. We need to find this out @kmille

**Comment by csimpi** [comment]
in the meantime, I went forward and found a way to get FLAC from Deezer. It's very difficult and would require some refactoring of the current app I am afraid. 
As I can see you'll need three requests in order to get what you need + a decrypt function to decrypt the downloaded encrypted file. 
I am not sure if this is the new API or the older way, but according to the web version it is using this API too. 

Get the CRSF token here using the `arl` cookie. (`response.results.checkForm`)

`http://www.deezer.com/ajax/gw-light.php`
```
{
        "api_version": "1.0",
        "api_token": "null",
        "input": "3",
        "method": "deezer.getUserData"
}
```

Get the song's token using the CRSF 
```
{
        "api_version": "1.0",
        "api_token": "{{deezer.AUTH.CRSF}}",
        "input": "3",
        "method": "song.getData",
        "sng_id": "379893661"
}
```

Get the decoded file:
```
{
    "license_token": "{{deezer.AUTH.license_token}}",
    "media": [
        {
            "type": "FULL",
            "formats": [
                { "cipher": "BF_CBC_STRIPE", "format": "FLAC" }
            ]
        }
    ],
    "track_tokens": ["{{deezer.TRACK.TOKEN}}"]
}
```

Decode:

https://github.com/korzhyk/deezer-decoder/blob/master/src/decoder.js


I'll put together a nodeJs project soon

**Comment by fsneew** [comment]
Hi there... Any news ? Same for me... Always 403 errors :-(

**Comment by Amrizamaa** [comment]
Bump

**Comment by kmille** [comment]
Still works for me. Do you use a ARL cookie of a free plan?

**Comment by Amrizamaa** [comment]
Yea it's works for free plan but it's sad because can't have in the hq ? like to  download maybe in flac or idk ? because with premiuim we can listen in flac but download idk

**Comment by kmille** [comment]
as far as I know: nope
